### PR TITLE
fix failed import of banks.json on macOS

### LINKED ISSUE #19: module does no load as expected on macOS version 11.1
It seems the module has failed to find the `db` on macOS

```js
Error: ENOENT: no such file or directory, open './db/banks.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at new NGBanks (/Users/macintosh/Documents/code/menji/node_modules/ng-banks/index.js:18:33)
    at Object.<anonymous> (/Users/macintosh/Documents/code/menji/node_modules/ng-banks/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './db/banks.json'
}
```
### Suggestion:
[At line 18](https://github.com/BolajiOlajide/ng-banks/blob/c3d7740b74696b608d4d94c2632fff337b324c87/index.js#L18) resolve the path using Node.js `path` module to run on all plateforms

### PR DESCRIPTION
**Pull request by micaiah-effiong**
resolve #19 using in-built `require` function

### CODE REVIEW

**Review by BolajiOlajide — APPROVED** [review]
Hey!
Thanks for creating this. I'm in the process of migrating this project to TS so I'll publish a patch build containing the fix here.

Thanks

**Comment by BolajiOlajide** [comment]
@micaiah-effiong New version published [here](https://www.npmjs.com/package/ng-banks)

**Comment by micaiah-effiong** [comment]
Alright, I'll be looking out for the TS version.
Any plans to add more banks?

**Comment by BolajiOlajide** [comment]
Yes, I should be done with the TS version by the end of this week. @micaiah-effiong 

As for the plans to add more banks, I'm open to PRs adding more banks - I don't have the bandwidth to source for that information right now but I'll happily accept contributions.

**Comment by micaiah-effiong** [comment]
I'll look into adding more banks. I'll open a PR when am done

**Comment by BolajiOlajide** [comment]
Alright. That works. 
Thanks

**Comment by BolajiOlajide** [comment]
@micaiah-effiong #21 completes migration of this project to typescript. Feel free to pull the new `main` branch and work from there.

**Pull request merged**
