### PR TITLE
Update banks and unit tests

### PR DESCRIPTION
**Pull request by micaiah-effiong**
- installed packages
- added all 66 banks as suported by Paystack
- added test case for getBank with bank code
- added prettier configuration
- added test for util functions

### CODE REVIEW

**Comment by micaiah-effiong** [comment]
@BolajiOlajide you can review the changes. The bank list shows all banks on Paystack bank API

**Comment by micaiah-effiong** [comment]
I'm still having a hard time coming up with `unique`, `3 letters` slug 🤦🏾‍♂️
For the Micro-finance Banks, I appended `-MFB` to the slug.

**Comment by micaiah-effiong** [comment]
## Suggestion 
Adding a bank type such as

- Retail banks.
- Commercial banks.
- Community development banks.
- Investment banks.
- Online and neobanks.
- Credit unions.
- Savings and loan associations.

would help to properly categorize the banks

**Review by BolajiOlajide — APPROVED** [review]
This looks good.
Thanks for adding the linter snd more tests.

I think it looks good. I'll fix the CI failure soon, it has to do with some tokens I deleted.

**Comment by BolajiOlajide** [comment]
Hey @micaiah-effiong 

Thanks for working on this. I made an edit to refactor the slug names but it's now published as `v2.1.1`. Thanks for the good work.

**Pull request merged**
